platform :ios, '10.0'

def guestLogix_pods
   use_frameworks!
   pod 'SkyFloatingLabelTextField', '~> 3.0'
   pod 'RMPickerViewController', '~> 2.3.1'
   pod 'KRActivityIndicatorView'
  end

target 'GuestlogixTechnicalTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  guestLogix_pods

  target 'GuestlogixTechnicalTestTests' do
    inherit! :search_paths
    guestLogix_pods
  end

end
